---
namespace: ciena
name: mdso
version: 1.1.4
readme: README.md
authors:
- Jeff Groom <jgroom@ciena.com>
description: Ansible collection to operate a Ciena MDSO server
license_file: LICENSE
tags: [ciena, saos, networking, ethernet, optical, tapi]
dependencies: {}
repository: https://github.com/ciena/ciena.mdso
issues: https://github.com/ciena/ciena.mdso/issues
