#!/usr/bin/env python
# Info module template

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by
#   https://github.com/jgroom33/vmware_rest_code_generator
#
# Do not edit this file manually.
#
# Changes should be made in the swagger used to
#   generate this file or in the generator
#
#############################################

from __future__ import absolute_import, division, print_function

__metaclass__ = type
import socket
import json

DOCUMENTATION = """
module: jobs_unclaimed_by_type
short_description: Handle resource of type jobs_unclaimed_by_type
description: Handle resource of type jobs_unclaimed_by_type
options:
  afterJobId:
    description:
    - The last jobId of the page preceding the desired page
    - Used by I(state=['get', 'head'])
    type: str
  maxCount:
    description:
    - Maximum number of jobs to return in a page
    - Used by I(state=['get', 'head'])
    type: int
  maxWait:
    description:
    - Maximum wait time in milliseconds before returning results
    - Used by I(state=['get', 'head'])
    type: int
  minCount:
    description:
    - Minimum number of jobs to return (unless maxWait is exceeded)
    - Used by I(state=['get', 'head'])
    type: int
  state:
    choices:
    - get
    - head
    description: []
    type: str
  type:
    description:
    - Job type
    - Required with I(state=['get', 'head'])
    - Used by I(state=['get', 'head'])
    type: str
author: []
version_added: 1.0.0
requirements:
- python >= 3.6
"""
IN_QUERY_PARAMETER = ["afterJobId", "maxCount", "maxWait", "minCount"]
from ansible.module_utils.basic import env_fallback

try:
    from ansible_module.turbo.module import AnsibleTurboModule as AnsibleModule
except ImportError:
    from ansible.module_utils.basic import AnsibleModule
from ansible_collections.ciena.mdso.plugins.module_utils.mdso import (
    gen_args,
    open_session,
    update_changed_flag,
)


def prepare_argument_spec():
    argument_spec = {
        "mdso_hostname": dict(
            type="str", required=False, fallback=(env_fallback, ["MDSO_HOST"])
        ),
        "mdso_username": dict(
            type="str", required=False, fallback=(env_fallback, ["MDSO_USER"])
        ),
        "mdso_password": dict(
            type="str",
            required=False,
            no_log=True,
            fallback=(env_fallback, ["MDSO_PASSWORD"]),
        ),
    }
    argument_spec["type"] = {"type": "str", "operationIds": ["get", "head"]}
    argument_spec["state"] = {"type": "str", "choices": ["get", "head"]}
    argument_spec["minCount"] = {"type": "int", "operationIds": ["get", "head"]}
    argument_spec["maxWait"] = {"type": "int", "operationIds": ["get", "head"]}
    argument_spec["maxCount"] = {"type": "int", "operationIds": ["get", "head"]}
    argument_spec["afterJobId"] = {"type": "str", "operationIds": ["get", "head"]}
    return argument_spec


async def main():
    module_args = prepare_argument_spec()
    module = AnsibleModule(argument_spec=module_args, supports_check_mode=True)
    session = await open_session(
        mdso_hostname=module.params["mdso_hostname"],
        mdso_username=module.params["mdso_username"],
        mdso_password=module.params["mdso_password"],
    )
    result = await entry_point(module, session)
    module.exit_json(**result)


def url(params):
    return "https://{mdso_hostname}/bpocore/market/api/v1/jobs/unclaimed/{type}".format(
        **params
    )


async def entry_point(module, session):
    func = globals()[("_" + module.params["state"])]
    return await func(module.params, session)


async def _get(params, session):
    _url = "https://{mdso_hostname}/bpocore/market/api/v1/jobs/unclaimed/{type}".format(
        **params
    ) + gen_args(params, IN_QUERY_PARAMETER)
    async with session.get(_url) as resp:
        content_types = [
            "application/json-patch+json",
            "application/vnd.api+json",
            "application/json",
        ]
        try:
            if resp.headers["Content-Type"] in content_types:
                _json = await resp.json()
            else:
                print("response Content-Type not supported")
        except KeyError:
            _json = {}
        return await update_changed_flag(_json, resp.status, "get")


async def _head(params, session):
    _url = "https://{mdso_hostname}/bpocore/market/api/v1/jobs/unclaimed/{type}".format(
        **params
    ) + gen_args(params, IN_QUERY_PARAMETER)
    async with session.head(_url) as resp:
        content_types = [
            "application/json-patch+json",
            "application/vnd.api+json",
            "application/json",
        ]
        try:
            if resp.headers["Content-Type"] in content_types:
                _json = await resp.json()
            else:
                print("response Content-Type not supported")
        except KeyError:
            _json = {}
        return await update_changed_flag(_json, resp.status, "head")


if __name__ == "__main__":
    import asyncio

    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
